- src/components/Navbar.tsx
> forgot to save test

- src/components/Navbar.tsx
> undoing test

- server/dist/chart_information.json
- server/src/chart_information.json
> adding larger json file to server

- app/src/state/actions/general-actions.ts
- server/src/index.ts
- server/src/load-packs.ts
- server/src/parse-map-packs.ts
- server/src/routes.ts
map images were built on server route which meant multiple users are impossible. changed to hold all datapack images in `public`
> Tsc 254 remove map image deleting on selection of datapack

- app/src/SettingsTabs/MapButtons.tsx
- server/__tests__/__data__/map-pack-keys.json
- server/__tests__/parse-map-packs.test.ts
- server/src/parse-map-packs.ts
- shared/src/index.ts
> connect transects to hash map

- app/src/state/actions/general-actions.ts
- app/src/state/initialize.ts
- server/src/file-metadata-handler.ts
- server/src/routes.ts
- server/src/types.ts
> reupdate file metadata on use of datapack

- app/src/NavBar.css
- app/src/NavBar.tsx
- app/src/SettingsTabs/Font.css
- app/src/SettingsTabs/Legend.css
- app/src/SettingsTabs/Legend.tsx
- app/src/components/TSCComponents.tsx
- app/src/constants.ts
- app/src/state/actions/general-actions.ts
- app/src/state/state.ts
- app/src/types.ts
> settings hover menu

- server/src/index.ts
- server/src/util.ts
Logs error to console and ends process when the jar file is missing or name is wrong compared to what's listed in the config.json file.
> TSC-46 Shows error on server when jar is missing

- app/src/SettingsTabs/MapButtons.tsx
- app/src/SettingsTabs/MapViewer.tsx
> Tsc 339 map point image display correction

- app/src/settings_tabs/AccordionPositionControls.tsx
- app/src/settings_tabs/ColumnMenu.css
- app/src/settings_tabs/ColumnMenu.tsx
- app/src/state/actions/column-actions.ts
Updated shift row buttons to fix alignment and included text to tell what buttons do
> Tsc 312 shift column order

- server/src/index.ts
- server/src/routes.ts
https://github.com/earthhistoryviz/tsconline/assets/104879321/2eac09cc-4743-4930-9436-5e883f827a65
demo
> Tsc 323 app route that serves all dev server routes

- app/src/Login.tsx
- app/src/settings_tabs/Datapack.tsx
- app/src/state/actions/general-actions.ts
fix the problem of uuid being undefined when requesting a download. Also, no file will be downloaded to user's computer if not logged in
https://github.com/earthhistoryviz/tsconline/assets/104879321/e0491008-a2ac-4725-a496-f149a83bff8f
> Tsc 373 fix download of datapack error

- app/src/state/actions/general-actions.ts
- app/src/state/parse-settings.ts
- shared/src/settings-types.ts
Load Settings now support settings files with only stages for top/base age
> Tsc 394 read settings should support non text ages stages for top and base age ranges

- app/src/state/actions/general-actions.ts
- app/src/state/actions/generate-chart-actions.ts
- app/src/util/error-codes.ts
changed to professor's preference of having top and base stage checks on generate rather than on input
> changed base/top age changes to check on generate

- app/src/ChartOptionsBar.tsx
- app/src/components/datapack_display/TSCCompactDatapackRow.module.css
- app/src/components/datapack_display/TSCCompactDatapackRow.tsx
- app/src/settings_tabs/Datapack.tsx
- app/src/settings_tabs/LoadSettings.tsx
- app/src/settings_tabs/SaveSettings.tsx
- app/src/state/state.ts
changes requested today
added tooltips to the save and load settings
changed save chart to be explicit
added compact datapack display
https://github.com/earthhistoryviz/tsconline/assets/89664317/5d5e93c9-25ea-49ca-b3a2-9ca9b0213570
> Small tweaks and changes to ui

- server/assets/config.json
https://github.com/earthhistoryviz/tsconline/assets/94872897/e498dbd7-5829-4d65-ac02-00969e416b26
Picture for comparison of last chart in video with bug:
> update config file

- app/src/util/coordinates.ts
https://github.com/user-attachments/assets/1c861f4e-cf2c-4ec0-a9e7-a07d55bb62e4
> fixed incorrect calculation of points for map points

- app/__tests__/__data__/parse-settings-keys.json
- app/__tests__/__data__/parse-settings-tests.json
- app/__tests__/parse-settings.test.ts
- server/__tests__/__data__/column-keys.json
- server/__tests__/parse-datapacks.test.ts
- server/src/parse-datapacks.ts
fixed tests 
added coverage for sequence columns
added subinfo to keys
> Tsc 444 fix parse settings tests

- app/src/components/TSCRadioGroup.tsx
- app/src/settings_tabs/column_menu/ColumnMenu.css
- app/src/settings_tabs/column_menu/ColumnMenu.tsx
- app/src/state/actions/column-actions.ts
- app/src/state/parse-settings.ts
- app/src/util/util.ts
- shared/src/constants.ts
- shared/src/index.ts
demo: 
https://github.com/user-attachments/assets/72372ccd-1d6d-45b6-8b80-ca935c3b0645
also I changed the default justification of Ma to "right" bc that's the default value in the jar. (and the default justification of any other age ruler is "left").
> Tsc 311 functionality to add blank age column

- .github/workflows/deploy-release.yml
workflow file for deployments to release
> Release 1.0

- app/src/settings_tabs/Results.css
- app/src/settings_tabs/Results.tsx
- app/src/util/util.ts
Changed logic of search tab
status column now has a checkbox or error icon
checkbox only shows up if age is within time interval and can be used to toggle columns
error icon shows up if age is not within time interval
https://github.com/user-attachments/assets/99563c7a-b7e6-4518-ae02-f67af5a0dd3b
> Tsc 461 event search change status to checkbox

- server/__tests__/admin-routes.test.ts
- server/__tests__/login-routes.test.ts
- server/__tests__/request-download-route.test.ts
- server/src/admin/admin-auth.ts
- server/src/admin/admin-routes.ts
- server/src/index.ts
- server/src/load-packs.ts
- server/src/routes/login-routes.ts
- server/src/routes/routes.ts
- server/src/routes/user-routes.ts
- vite.config.ts
moving all routes into more specific directories
> refactored routes (ignore)

- app/src/settings_tabs/Results.css
- app/src/settings_tabs/Results.tsx
- app/src/settings_tabs/Search.css
- app/src/settings_tabs/Search.tsx
- app/src/state/actions/column-actions.ts
- app/src/types.ts
Changed label of "status" column to "column on?"
changed label of "qualifier" to "type"
changed time display to a table for line up
> Tsc 485 event search minor changes

- app/src/About.tsx
> Updated about with Michael

- app/src/state/actions/admin-actions.ts
- server/__tests__/admin-routes.test.ts
- server/src/admin/admin-auth.ts
bug fixes, will just merge after tests complete
> added fixes for deleting a datapack and added official datapack renaming

- app/src/DatapackProfile.tsx
- app/src/components/datapack_display/DatapackUploadForm.tsx
- server/__tests__/upload-handlers.test.ts
- server/src/upload-handlers.ts
- shared/src/constants.ts
- backend limits fields for datapack upload
- tests included
> Limit fields backend and tests

- app/src/NavBar.css
- app/src/NavBar.tsx
- app/src/settings_tabs/Datapack.module.css
- app/translation/en.json
https://github.com/user-attachments/assets/6f1b792c-cacd-4390-98b9-40c4fbdd435b
> implemented mobile functionalityfor navbar

- app/src/NavBar.css
- app/src/NavBar.tsx
- app/src/account_settings/Profile.tsx
- app/src/theme.ts
removed dark/light mode & language from profile
added preferences tab
> Tsc 520 changes to account menus

- app/src/settings_tabs/Column.tsx
> tooltip in column accordion spelled wrong

- app/src/Presets.tsx
- shared/src/index.ts
> fix presets lagging

- .github/workflows/deploy-dev.yml
- server/assets/config.json
- removes extra jar files from the server
- uploads jar file to dropbox on merge and clears old jars (excluding 2 most recent and decryption)
- at some point swap credentials out since they are mine
> Tsc 625 remove jars upload dropbox

- server/assets/config.json
> change config file

- app/src/Chart.css
- app/src/Chart.tsx
- app/src/ChartOptionsBar.tsx
- app/src/assets/icons/axes=one.svg
- app/src/assets/icons/axes=two.svg
- app/src/assets/icons/model=Default.svg
- app/src/assets/icons/model=model.svg
- app/src/components/TSCColorPicker.tsx
- app/src/components/TSCCrossPlotSVGComponent.tsx
- app/src/crossplot/CrossPlotChart.tsx
- app/src/crossplot/CrossPlotSideBar.module.css
- app/src/crossplot/CrossPlotSideBar.tsx
- app/src/state/actions/crossplot-actions.ts
- app/src/state/actions/general-actions.ts
- app/src/state/state.ts
- app/src/types.ts
* added markers (different from models)
* have ingrained tooltips into the svg and apply the circle marker on the svg itself
* multiple types, ability to change the age/depth (positioning) of the marker
* change color
* click to remove
* toolbar options are now dynamic for the chart so we can change them as we see fit for cross plot and regular chart
* as normal there is no mobile, that will be new task bc too big if i did that here
https://github.com/user-attachments/assets/112aff5e-9ee7-4551-9bc8-ab78aaf59b7f
> Tsc 619 dot creation

- app/src/App.tsx
- app/src/constants.ts
- app/src/theme.ts
> add the base implementation for the dde theme changes

- server/src/db/london/json-to-txt.ts
- create data column groups based on path
> 477 london organize columns based on path
