earthhistoryviz/tsconline

app/src/SettingsTabs/Legend.tsx
app/src/state/actions/GeneralActions.ts
app/src/state/state.ts
server/src/index.ts
server/src/load-packs.ts
server/src/routes.ts
server/tsconfig.json

changes reflected in 3/1 meeting
patterns now load on `yarn start`
patterns sorted when loaded into `app`
filter default to `presentInMap` and `alphabetical`
more refactoring on the server side to make `index.ts` cleaner

default filter changes, sort on load, patterns on load

---

app/src/state/actions/generate-chart-actions.ts
server/__tests__/__data__/column-keys.json
server/src/parse-datapacks.ts

this is the comment about the "hack"
```
/**
* Since we hash by name only to allow consistency between facies maps and
* the column page, a generic like Facies Label will cause errors.
* The solution @Paolo came up with is to prepend the name of the parent
* and change before the conversion to xml. The downside is we must check
* every ColumnInfo object which may cause problems with time consistency.
* However, this is asyncronous, which makes it less likely to cause problems.
* @param column
*/
```
java file ^
https://github.com/earthhistoryviz/tsconline/assets/89664317/5ca55d3e-1c7b-4835-a9b1-bd649467f08b

manually append facies columns

---

app/src/SettingsTabs/ColumnMenu.tsx
app/src/SettingsTabs/FontMenu.tsx
app/src/state/actions/general-actions.ts
app/src/state/actions/generate-chart-actions.ts
server/__tests__/__data__/column-keys.json
server/__tests__/__data__/parse-datapacks-test-2.txt
server/__tests__/parse-datapacks.test.ts
server/src/parse-datapacks.ts
shared/src/constants.ts
shared/src/index.ts

depending on the column type, the font options that should show for the font menu are now correctly set
the java program tends to give all font options when given a column type that isn't recognized, but i did some trial and error to find out what actually matters in those columns and whittled it down. this could be wrong so i added todos for future reference. Depending if it is a meta column or an actual leaf column, different font menus will be shown.
also chron columns consist of multiple columns so i added functionality for that. 
also added `subTransect` onto `ColumnInfo` since it wasn't there before (bug)

font options should be recursively set in the parsing of datapacks, chron multi column capability, subTransect fix

---

app/src/SettingsTabs/ColumnMenu.css
app/src/SettingsTabs/ColumnMenu.tsx
app/src/SettingsTabs/FontMenu.tsx
app/src/SettingsTabs/MapButtons.tsx
app/src/components/TSCCheckbox.tsx
app/src/state/actions/column-actions.ts
app/src/state/actions/general-actions.ts
app/src/state/actions/generate-chart-actions.ts
app/src/state/parse-settings.ts
app/src/util/error-codes.ts
server/__tests__/__data__/column-keys.json
server/__tests__/parse-datapacks.test.ts
server/src/parse-datapacks.ts
shared/src/index.ts

- fixed font changes with inheritance and backend restructuring
- font inheritance works, (doesn't show the children inheriting on the front end but changes xml to chart propogation)
- added enable title checkbox
- removed some general parse setting assumptions
- added error if no columns are selected on generation
- added error if all charts have unit ranges of 0 (top: 0, base: 0)
- added column types for display (Zone, MetaColumn, etc)
- refactored a lot of the code to now parse datapacks that are LONE which means they do not have a parent-child hierarchy
https://github.com/earthhistoryviz/tsconline/assets/89664317/249ac527-046f-4bb5-8143-6e8287c59d73

 font inheritance, enable title, more error checking, column types, lone columns

---

app/src/SettingsTabs/Font.css
app/src/SettingsTabs/Font.tsx
app/src/SettingsTabs/FontMenu.css
app/src/SettingsTabs/FontMenu.tsx
app/src/state/actions/general-actions.ts

this is the fonts tab in the java file that allows you to change the font options for the whole chart (every possible unit/chart inside chart root)
basically used `FontRows` that's used for individual columns, but locked it if it was `Chart Root`
i've made it so it only displays the font menu rows that apply to the whole chart (not default all)

Tsc 295 general chart fonts change chart root

---

app/src/Home.tsx
app/src/NavBar.tsx
app/src/SettingsTabs/BackgroundColor.tsx
app/src/SettingsTabs/ColumnMenu.tsx
app/src/SettingsTabs/EditWidthField.tsx
app/src/SettingsTabs/Font.css
app/src/SettingsTabs/FontMenu.css
app/src/SettingsTabs/FontMenu.tsx
app/src/SettingsTabs/MapControls.css
app/src/components/TSCSnackbar.css
app/src/components/TSCSnackbar.tsx
app/src/state/actions/general-actions.ts
app/src/state/actions/generate-chart-actions.ts
app/src/state/initialize.ts
app/src/util/error-codes.ts
server/__tests__/__data__/column-keys.json
server/__tests__/__data__/parse-datapacks-test-2.txt
server/__tests__/parse-datapacks.test.ts
server/src/index.ts
server/src/parse-datapacks.ts
server/src/routes.ts
shared/src/index.ts

* Fixed default setting application on datapacks with different units
* Popup for default age only shows if not on the settings tab or on the settings tab with data pack tab selected
* Popup also includes vertical scale ( ask aaron if we want to include this in the popup directive? )
* Other properties are parsed in the data pack (vertical scale, date, etc)
* Deprecated the data pack age info to flatten the information for easier use
* Column background doesn’t show if not applicable
* Fixed dot text field padding in map points (issue opened up that the value in the text box can't be controlled from outside but that's a minor bug, functionality still works)
* Profiling for ui stalling due to fetching all datapacks from the server lead to an implementation of chunk loading during the fetch …

bug fixes, grab datapack properties if it exists from datapack, apply defaults, chunk loading datapack info

---

app/__tests__/data-mining.test.ts
app/src/settings_tabs/EditNameField.tsx
app/src/settings_tabs/advanced_settings/DataMiningSettings.tsx
app/src/state/actions/column-actions.ts
app/src/state/actions/general-actions.ts
app/src/state/parse-settings.ts
app/src/types.ts
app/src/util/data-mining.ts
app/src/util/util.ts
server/__tests__/__data__/column-keys.json
server/__tests__/parse-datapacks.test.ts
server/assets/config.json
server/src/parse-datapacks.ts
shared/src/constants.ts
shared/src/index.ts
shared/src/settings-types.ts

- does not include reading settings xml to create a new column yet (TSC-370)
- new xml tag in column tag `isDataMiningColumn` will let you know if this was generated from the datapack or by another column
- fix for if there are no column relationships in file and if it just contains "blocks" or "lone columns"
- created datamining that mimics that of the java file to appropriately scale the new columns
- tests for above
- added fields to parsing of events (FAD, LAD, EVENT, EVENTS)
- can clear the field to remove the added column
- selecting any data mining option will create that column and subsequent clicks on other radios will remove and add respectively
- fixed parent relationship bug that it wasn't getting set on multiple datapacks being added together …

support for customization of data mining column on the front and backend and datamining range calculations

---

app/__tests__/__data__/parse-settings-keys.json
app/__tests__/__data__/parse-settings-tests.json
app/__tests__/parse-settings.test.ts
app/src/components/TSCGenericSettings.tsx
app/src/settings_tabs/advanced_settings/RangeSpecificSettings.tsx
app/src/settings_tabs/column_menu/ColumnMenu.tsx
app/src/state/actions/column-actions.ts
app/src/state/parse-settings.ts
server/__tests__/__data__/column-keys.json
server/src/parse-datapacks.ts
shared/src/constants.ts
shared/src/index.ts
shared/src/settings-types.ts

added tests and fixed type misunderstandings for `chron` as well
fixed placeholder text from displaying `Enter size` generically

range margin, age pad, and range sort

---

app/src/admin/Admin.tsx
app/src/admin/AdminDatapackConfig.tsx
app/src/admin/AdminUserConfig.tsx
app/src/components/datapack_display/TSCDatapackUploadForm.tsx
app/src/settings_tabs/Datapack.tsx
app/src/state/actions/admin-actions.ts
app/src/state/actions/general-actions.ts
app/src/state/state.ts
app/src/util/error-codes.ts
server/__tests__/__data__/column-keys.json
server/__tests__/admin-routes.test.ts
server/src/admin-auth.ts
server/src/admin-routes.ts
server/src/index.ts
server/src/load-packs.ts
server/src/parse-datapacks.ts
server/src/routes.ts
server/src/types.ts
server/src/util.ts
shared/src/index.ts

changed user datapacks to associate uuids instead of `isUserDatapack`
removed `removeDevDatapacks` which used to remove dev datapacks in a hidden config file
thought that was too messy if they could upload a dev datapack after removing it with new description/titles then if the server restarts, you lose that information more or less
now make `root` datapacks unremovable and `root` users unremovable
might want to make a root table for users but i don't see us using more than one
changed a lot of the tests to this new implementation
however, everytime i save `column-keys.json` it reformats the whole file, i'm not sure why 😭 large file change there but it's just changing `isUserDatapack` to nothing since `uuid` is `undefined` and we use that instead. …

Tsc 447 admin datapack config frontend

---

app/src/settings_tabs/map_points/MapPoints.tsx

world map always be the first, then all parents map shown in the alphabetic order, then their children

Tsc 448 sort maps so that parent maps are at the top

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-preview.yml
.github/workflows/deploy-release.yml
.github/workflows/merge-pipeline.yml
server/src/routes.ts

listen to docker logs for if the server restarts/starts properly
add some proper error checking for if `/confirm-deploy` gets called by itself and more specific docker querying for current running containers
not sure why but it doesn't use my workflow file when commenting so i can't for sure test it until it merges to main
although i tested all the commands in the console (and checked that it deploys/listens when deploying to development)

Tsc 467 make deploy actions listen to docker logs to return errors properly

---

app/src/state/actions/general-actions.ts
app/src/state/actions/generate-chart-actions.ts
app/src/state/initialize.ts
app/src/util/error-codes.ts
server/src/file-metadata-handler.ts
server/src/index.ts
server/src/routes.ts
shared/src/index.ts

- just some back end fixing for making sure that errors are caught properly when updating a datapack's metadata when a chart is used. 
- one thing to note is that if for some reason a file exists and the metadata does not note this, i'm not sure what to really do so it cancels the chart request. i would normally want to make the entry if it doesn't exist, but that feels like a lot of spaghetti code since we have to verify whether the datapack is valid, all the parts are present, etc (basically the whole upload workflow) so i thought it would be better to just cancel and if errors persist with the metadata, we manually add it (or create a route to verify and add the entry) for admins
- additionally changed fetching user datapacks and fetching server datapacks into their own seperate calls …

Tsc 468 fix update file metadata on datapack usage when generating a chart

---

app/src/ChartOptionsBar.tsx
app/src/state/actions/general-actions.ts
app/src/state/actions/generate-chart-actions.ts
app/src/state/state.ts

- the sanitization of the svg makes the downloadable svg catch errors
- could unsanitize, but this way it's a 1:1 with the export
- store the unsafe svg for download use only
- see below for errors
- svg download is now normal/the same as the export of the java file

add unsafe content for download so svg downloads and displays properly

---

app/src/NavBar.tsx
app/src/components/TSCError.tsx
app/src/components/datapack_display/TSCCompactDatapackRow.module.css

- clickable cursor pointer on `TSCDatapackCompactRow`
- divider has error color on `TSCError`

Tsc 491 change error text to black and make bigger

---

scripts/stress_test.py
server/package.json
server/src/file-metadata-handler.ts
server/src/index.ts
yarn.lock

Added mutex to metadata handler to fix race condition. After testing a max of 2 for concurrency and a queue size of 30 seemed best, increasing the concurrency anymore leads to a large increase in timeouts.
Example with 2 and 30 as values:
Simulating 50 users pinging the endpoint
Number of successful responses (200): 49
Number of timeouts (408): 0 - []
Number of server busy (503): 0 - []
Number of gateway timeouts (504): 0 - []
Other errors: [('south_america', 200, '{"error":"Unknown error occurred during chart generation"}')]
Number of matching responses: 49
Number of mismatching responses: 0
Average response time of chart request: 108.65 seconds
When increased to concurrency of 3:
Simulating 50 users pinging the endpoint
Number of successful responses (200): 37
Number of timeouts (408): …

TSC-471-concurrency-stress-testing

---

app/src/App.tsx
app/src/state/actions/general-actions.ts
app/src/state/state.ts

- this adds logic to dark mode cookies/system preferences
- will load regard preference regardless of user status (logged in or not)
- if user has manually switched one or the other, it won't change when changing system preferences
- potentially will have a task to create light, dark, and system modes so that they stay seperate although that use case is so small and could not be worth the time of the nuanced logic.
https://github.com/user-attachments/assets/24b536f5-ebe7-4675-9c99-e19aa0b7bd1d

add logic for system preference listening and local storage checking

---

app/src/settings_tabs/Results.tsx
app/src/settings_tabs/map_points/MapButtons.tsx
app/src/settings_tabs/map_points/MapViewer.tsx
app/src/util/util.ts
app/src/util/workers/set-datapack-config.ts

- Simple fix for hierarchy which only caused one datapack's information to be shown in a parent
- another fix for column on display for mappoints (refactored the `Event Search` to use the same function)
- This makes it so the path checks all parents if they are on, then displays the correct icon based on that path instead of the on/off of itself.

add fix for map point display and for map point hierarchy bug

---

app/__tests__/parse-settings.test.ts
app/src/settings_tabs/SaveSettings.tsx
app/src/state/actions/generate-chart-actions.ts
app/src/state/actions/util-actions.ts
app/src/state/parse-settings.ts
app/src/state/state.ts

changed manual changes to the columns for writing/loading to be included in `jsonToXml`
fixes gabi's problem where saving a settings file and loading the same settings file on the website produces an error/does not produce correct results
since we change `Facies` and `Series Label` to include the parent name and need to remove it when writing ( we did it on chart generation, but since we do the same thing/need the same thing for the writing to file we move those manual changes into the write file function )

fix problem with manually loading columns

---

app/src/state/actions/admin-actions.ts
server/__tests__/admin-routes.test.ts
server/src/add-dev-config.ts
server/src/admin/admin-config.ts
server/src/admin/admin-routes.ts
server/src/index.ts
server/src/load-packs.ts
server/src/routes/routes.ts
server/src/types.ts
server/src/util.ts

- made loading/removing a datapack modular for ease of use in testing and in making atomic (for when we do edits)
- fix after uploading a server datapack, it doesn't add the correct datapack to the index
- fix for spaces in title name saving to the correct directory/name in the filesystem when decrypting

Tsc 522 add assets config class function implementation that makes it more modular easier to test

---

server/__tests__/user-handler.test.ts
server/__tests__/user-routes.test.ts
server/src/file-metadata-handler.ts
server/src/routes/user-auth.ts
server/src/routes/user-routes.ts
server/src/user/user-handler.ts
shared/src/index.ts
vite.config.ts

- basically just backend changes
- all fields that you upload a file with are editable (both use `DatapackMetadata`)
- outsourced changing files into `user-handler.ts`
- made tests for each
- will work on front end for this in another pr
- also don't know if admins should be allowed to edit other people's datapacks but that's probably not something we want.

Tsc 533 edit datapack information

---

.github/workflows/merge-pipeline.yml
package.json

- dependabot will no longer checkout code from bitbucket
- dependabot will exclude encryption tests
- added script in package.json for running all tests except for encryption test
^ build-and-test action for "Bump rollup from 4.17.2 to 4.24.0" (dependabot PR)

Dependabot Fix

---

app/src/settings_tabs/Datapack.module.css
app/src/settings_tabs/Datapack.tsx
app/translation/en.json

* added wrapping to datapacks page
* added see more/see less when there are more than 9 datapacks (for official it is 18 because it wraps)
* demo shows 6 to illustrate my point but with that it still seems like a lot when looking at the non compact
* let me know if 9 is too much or if i should go with 6. the compact isn't really the issue, the bigger row one might be a lot of datapacks at once, but tbh if you're on that page you want more info anyways
* 
https://github.com/user-attachments/assets/100b9086-0212-46d4-9507-bd5cf8b05afd

Tsc 565 add more compact datapack rows

---

app/src/DatapackProfile.tsx
app/src/Presets.tsx
app/src/settings_tabs/Datapack.tsx
app/src/state/actions/admin-actions.ts
app/src/state/actions/general-actions.ts
app/src/state/non-action-util.ts
server/__tests__/admin-routes.test.ts
server/__tests__/user-routes.test.ts
server/src/admin/admin-auth.ts
server/src/admin/admin-routes.ts
server/src/index.ts
server/src/routes/routes.ts
server/src/routes/user-routes.ts

- can refresh on datapack pages now
- changed private official datapacks to now only send metadata on page load for admins and when clicked on do the actual fetch (was causing lots of problems with timing issues and recaptcha on datapackProfile). admin page still uses the fetch all route

added refreshing to datapack profile

---

server/__tests__/upload-handlers.test.ts
server/__tests__/user-handler.test.ts
server/src/migrate-cached-datapacks.ts
server/src/public-datapack-handler.ts
server/src/upload-handlers.ts
server/src/user/fetch-user-files.ts
server/src/user/user-handler.ts

* for @JacquiFreeElectron and @lbostre 
* datapacks in `/[uuid]/datapacks/[title]`
* small change that will be changed in two weeks, i'll comment on it below -> removes all files besides datapacks in someone's `uuid` directory to get rid of the previous datapacks in previous structure `[uuid]/[title]`

Tsc 633 datapacks in UUID dir

---

app/src/crossplot/CrossPlotChart.tsx
app/src/crossplot/CrossPlotSideBar.tsx
app/src/state/actions/crossplot-actions.ts
app/src/state/state.ts

this properly makes the revert button work
known issue: expanding the column and pressing revert will revert the expansion in some cases. no real way around this tbh
i track the dirty state manually in each action. I tried using reactions but it seems against the philosophy of reactions to make changes to the observable AND it doesn't work after a while debugging
https://github.com/user-attachments/assets/8f58d981-783c-4804-a15b-a08c57c12649
Closes 410

revert changes properly

---

app/src/settings_tabs/Time.css

css was using justify-self, which works in some browsers but not others (e.g. firefox).
https://stackoverflow.com/questions/49658425/flexbox-justify-self-flex-end-not-working
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_box_alignment/Box_alignment_in_flexbox#there_is_no_justify-self_in_flexbox

fix time setting centering issue on firefox
